### ISSUE TITLE
Missing spec links for MediaStream, MediaStreamTrack, and DOMHighResTimeStamp

### ISSUE THREAD

**Issue by rtoy** [speced/bikeshed#1190]
The [WebAudio spec](https://webaudio.github.io/web-audio-api/) references MediaStream, MediaStreamTrack, and DOMHighResTimeStamp types, but bikeshed doesn't know where to get them.

MediaStream and MediaStreamTrack are defined in [Media Capture and Streams spec](https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-mediastream)

DOMHighResTimeStamp is in [High Resolution Time Level 2](https://w3c.github.io/hr-time/#dom-domhighrestimestamp)

**Comment by rtoy** [comment]
A workaround:  `{{MediaStreamTrack}}` can be replaced with `[[mediastream-capture#mediastreamtrack|MediaStreamTrack]]`.  Similarly for `MediaStream`.

**Comment by jyasskin** [comment]
I think the root cause here is covered by #2453. The concrete problem has gotten fixed over time.
