### ISSUE TITLE
Add a non-normative container that gets stripped in the output

### ISSUE THREAD

**Issue by domenic** [speced/bikeshed#1193]
I try to liberally use `<div class="non-normative">` or `<span class="non-normative">` to help with normative reference and accidental 2119 detection. But, this ends up in my output.

This doesn't impact anything visually, but feels a bit unclean. It'd be nice if there were a way to mark up something as non-normative without impacting the built result.

(Understandably, this is pretty low priority.)

**Comment by tabatkins** [comment]
Are you ok with adding more markup, like an attribute saying to remove the element from the output (and promote its children)? Or would you prefer a shorthand specifically for this purpose?

**Comment by domenic** [comment]
Extra markup sounds totally fine.

**Comment by jyasskin** [comment]
Same as #954, right?

**Comment by jyasskin** [comment]
Duplicate of #954.
