### ISSUE TITLE
Show how to link to a term

### ISSUE THREAD

**Issue by jyasskin** [speced/bikeshed#1319]
For example, when trying to link to https://mimesniff.spec.whatwg.org/#mime-type-essence, I wind up using Chrome's inspector to reveal that the element is 

```html
<dfn class="dfn-paneled" data-dfn-for="MIME type" data-dfn-type="dfn"
data-export="" id="mime-type-essence">essence</dfn>
```

From which I conclude that the right link is `[=MIME type/essence=]` and that there aren't any other `lt`s I can use to refer to it.

It'd be nice to be able to see that information from the dfn panel. However, nobody but other spec authors cares, so it probably shouldn't be shown by default.

**Comment by tabatkins** [comment]
Right, that's about the best way to figure out term linking right now. Alternately one can use use `bikeshed refs`:

```
> bikeshed refs --text="essence"
status:    current
for:       [MIME type]
level:     1
url:       https://mimesniff.spec.whatwg.org/#mime-type-essence
type:      dfn
export:    True
text:      essence
shortname: mimesniff
normative: True
spec:      mimesniff
```

But yeah, exposing this data somehow would be interesting. @jakearchibald is asking for a vaguely-related "power feature" for definitions in #1321; maybe I could put some icons at the bottom of the dfn panels?

**Comment by jyasskin** [comment]
Unfortunately, `bikeshed refs --text contains` doesn't discover that https://fetch.spec.whatwg.org/#header-list-contains is also accessible via `[=header list/does not contain=]`.

Icons with tooltips sound fine for power features.

FWIW, #1321 sounds like a good behavior for the *default* click on a term: a lot of times non-power-users don't need to lose their context in the source standard just to figure out what a term meant.
