### ISSUE TITLE
Use sentence case in headings

### ISSUE THREAD

**Issue by npm1** [speced/bikeshed#1609]
Example: in https://w3c.github.io/paint-timing/ we have "Normative References" and "IDL Index" which I think are auto generated by Bikeshed. These should be in sentence case instead.

**Comment by jyasskin** [comment]
(I'm not taking a position on which casing should be the default. As @tabatkins said, https://w3c.github.io/manual-of-style/ doesn't take a position, so this should probably be resolved by a discussion on spec-prod.)

**Comment by tabatkins** [comment]
I take a moderately strong position that headings should be in title case; if they have a colon, the stuff after is in sentence case. The CSSWG uses this formatting, for instance. Bikeshed just reflects this with its autogenerated headings.
