### ISSUE TITLE
Strip markup from <meta content="">

### ISSUE THREAD

**Issue by fantasai** [speced/bikeshed#1655]
The Abstract metadata gets used directly in the abstract section, but you've also started adding it to `<meta name="abstract" content="...">`; however you're not stripping HTML markup from the contents of that attribute, so the metadata includes escaped markup which is *definitely* not what's wanted there.

**Comment by fantasai** [comment]
Sample output:

```
  <meta content="This module contains the features of <a href=&quot;https://www.w3.org/TR/CSS/&quot;>CSS</a> relating to the alignment of boxes within their containers in the various CSS box layout models: block layout, table layout, flex layout, and grid layout. (The alignment of text and inline-level content is defined in [[CSS-TEXT-3]] and [[CSS-INLINE-3]].)" 
```

**Comment by tabatkins** [comment]
I mean... is it not? I'm not even sure what consumes the `<meta name=abstract>`, if anything. It's there because Bert's processor added it, iirc.

**Comment by fantasai** [comment]
If nothing consumes it, then let's not emit it? :)

**Comment by tabatkins** [comment]
At this point it's not even injected into any of the boilerplates, so yeah, removing it entirely now.
