### ISSUE TITLE
Python 3.7 dependency causes problems

### ISSUE THREAD

**Issue by svgeesus** [speced/bikeshed#1661]
On Ubuntu 18.04 running on Windows Subsystem for Linux (which comes with Python3 as the default Python):

> chris3@Nomad: /GitHub$ sudo apt-get upgrade python3
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> python3 is already the newest version (3.6.7-1~18.04). 

Am thus unable to install bikeshed to generate the Web Audio API spec.

Oh, and I used a Git checkout of Bikeshed, because

> chris3@Nomad: $ sudo pip3 install bikeshed
> [sudo] password for chris3:
> Collecting bikeshed
>   Could not find a version that satisfies the requirement bikeshed (from versions: )
> No matching distribution found for bikeshed

**Comment by svgeesus** [comment]
Oh and on Cygwin, recently updated:

> Chris@Nomad /cygdrive/c/Users/Chris/Documents/GitHub
> $ python3 --version
> Python 3.6.9

**Comment by svgeesus** [comment]
and (on Cygwin, where the previous, Python-2-happy Bikeshed was still installed)

> Chris@Nomad /cygdrive/c/Users/Chris/Documents/GitHub/web-audio-api
> $ bikeshed spec
> Traceback (most recent call last):
> File "/usr/bin/bikeshed", line 6, in <module>
>    from pkg_resources import load_entry_point
>  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
>    @_call_aside
>  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
>    f(*args, **kwargs)
>  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3263, in 
> _initialize_master_working_set
>    working_set = WorkingSet._build_master()
>  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
>    ws.require(__requires__)
>  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
>    needed = self.resolve(parse_requirements(requirements))
>  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
>    raise DistributionNotFound(req, requirers)
>  pkg_resources.DistributionNotFound: The 'Bikeshed' distribution was not found and is required 
>  by the application

**Comment by svgeesus** [comment]
Oh and using the online tool doesn't work because of include files

> Error running preprocessor, returned code: 1.
> [1;31mFATAL ERROR:[0m Couldn't find include file 'audionode.include'. Error was:
> [Errno 2] No such file or directory: '/tmp/audionode.include'
> [7;31m ✘ [0m Did not generate, due to fatal errors

**Comment by svgeesus** [comment]
And attempting to follow the advice in the documentation to use pyenv (this on Ubuntu 18.04 on WSL)

> chris3@Nomad:~/GitHub$ sudo apt-get install pyenv
> [sudo] password for chris3:
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package pyenv

**Comment by svgeesus** [comment]
It is possible to [install Python 3.7 by adding a new PPA](https://linuxize.com/post/how-to-install-pip-on-ubuntu-18.04/) but that doesn't help as Python 3.6 is still there.

> chris3@Nomad:~/GitHub$ python3 --version
> Python 3.6.9
> chris3@Nomad:~/GitHub$ python3.7 --version
> Python 3.7.7
> chris3@Nomad:~/GitHub$ pip3 --version
> pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

**Comment by blakev** [comment]
@svgeesus In your last comment you can access `pip` via 3.7 like, `$ python3.7 -m pip --help`

Since you have a Python3.7 version installed you can also create a virtual environment,

```bash
$ python3.7 venv ./env
$ source ./env/bin/activate
(env) $ pip install (whatever)
...
```

**Comment by jyasskin** [comment]
I think the default versions of Python have increased enough that this is no longer a problem.
