### ISSUE TITLE
Keyboard accessibility issue

### ISSUE THREAD

**Issue by frivoal** [speced/bikeshed#1681]
refiled form https://github.com/w3c/csswg-drafts/issues/1925

> the "asides" rendered as tooltips (see for instance the "all", "print", "screen", "speech" in https://www.w3.org/TR/mediaqueries-4/#media-types) cannot be triggered using the keyboard.

**Comment by jyasskin** [comment]
Specifically, the problematic `<aside>`s here are the dfn-panels that appear when you click on a `<dfn>`?

**Comment by dlaliberte** [comment]
I'm thinking the display of these asides should be integrated with the link hints that I am working on.  This means we would convert the dfn-paneled element to an anchor, which could then be focused on normally, by mouse or keyboard.  The aside panel could then be used as the tooltip, probably with a style that is more like the tooltip style I am using.

Actually, this change could happen before all the rest of the link hints changes.

**Comment by tabatkins** [comment]
The problem, ultimately, is that the popups need to be some sort of block element (`aside` is the most appropriate) but the HTML parser auto-closes `p` upon seeing them, so it's simply not possible to statically put them in the correct place for keyboard accessibility.

...tho now that I type that out, I realize we could absolutely move them there with JS on page load.
