### ISSUE TITLE
Railroad diagram transformation adds invalid "xlink" attribute

### ISSUE THREAD

**Issue by tidoust** [speced/bikeshed#2319]
The [Minor fixes to railroad code](https://github.com/tabatkins/bikeshed/commit/f8e0361e5990ad1a57abd99425f90c7e4907f47c) introduced last week make Bikeshed add an `xlink` attribute to the generated `<svg>` element. That is invalid in an HTML document (the [HTML test file](https://github.com/tabatkins/bikeshed/blob/f8e0361e5990ad1a57abd99425f90c7e4907f47c/tests/github/WICG/background-fetch/index.html) typically does not pass HTML validation because of that).

Via https://github.com/gpuweb/gpuweb/issues/3222

**Comment by tabatkins** [comment]
Ah, so this was done in the preceding commit <https://github.com/tabatkins/bikeshed/commit/7422becf4986cfe1a0b8cad5b1061dc9a86a11ea> (I just refreshed the tests in the commit you found).

But this should have just been a direct port of the current library code, which suggests that I've messed things up over there as well, hm.

**Comment by fantasai** [comment]
This is blocking republication of css-images-4, btw.
https://labs.w3.org/echidna/api/status?id=92b9872d-1ac9-47aa-ad13-6c6a6f906446
