### ISSUE TITLE
Linter complains about using tabs for indentation and spaces for alignment :(

### ISSUE THREAD

**Issue by fantasai** [speced/bikeshed#2436]
Seeing as using tabs for indentation and spaces for alignment is unquestionably the best way to handle white space in the document ;) I am hereby objecting to having Bikeshed's linter throw warnings about it.

(Are you trying a stealth campaign for us to switch to space indentation or what?)

**Comment by tabatkins** [comment]
It shouldn't, since I do that too. What source for us if complaining about?

**Comment by fantasai** [comment]
css-text-4/Overview.bs

**Comment by tabatkins** [comment]
I've repeatedly started on fixing this for the last few weeks and then immediately gotten distracted. Finally fixed; it now only complains if you have tabs *after* spaces, and the error message is a little more clear about the problem.

**Comment by fantasai** [comment]
@tabatkins I'm still getting an error on https://github.com/w3c/csswg-drafts/blob/dcbdd6d55b66bdbf4c98633d4229998945a70b37/css-images-4/Overview.bs#LL2528C4-L2528C4 btw

**Comment by tabatkins** [comment]
Hm, this version of the error is more difficult to deal with; it's happening because I've already stripped out the indentation that the list required, so I don't see the preceding tabs at all, just the space.

**Comment by tabatkins** [comment]
Okay, I moved mixed-indent linting to happen *before* markdown parsing, so it doesn't get invoked within nested contexts.
