### ISSUE TITLE
Remove the automatic link to Shepherd test results

### ISSUE THREAD

**Issue by svgeesus** [speced/bikeshed#2450]
Bikeshed currently adds an automatic test widget to CSSWG specs, both on drafts.csswg.org and on W3C /TR. This *used* to be very helpful, giving an implementation report broken out by spec section.

Given that:

1. The tests that it reports on are now [missing more than **2 years** of additions, corrections and updates](https://github.com/w3c/csswg-drafts/issues/6896)
2. The reports rely on manual test running by an actual person, which I previously saw as a good use of my time and now don't because running a known-incorrect test has no value
3. The tests and the reports give an inaccurate and very negative view of the state of implementation
4. There is [no prospect](https://github.com/w3c/csswg-drafts/issues/6896#issuecomment-1299169289) of the Shepherd test situation improving (the recent "month of work" to stop the drafts server falling over all the time did not include any work on the test area)
5. The presence of the widget encourages people to run tests, and they will then draw inaccurate conclusions or even change implementations "to pass" known incorrect tests.

Then adding this link to all CSSWG specs has **negative value** and I am asking that Bikeshed remove (comment out code that adds) this widget. If at some future time it starts working again it can always be added back.

**6237** well maintained tests? Or **118** out of date ones?

![image](https://user-images.githubusercontent.com/2506926/214897746-77f2f5e8-14dd-4b0e-b97d-93d8ac3235da.png)

Related:
 - https://github.com/tabatkins/bikeshed/issues/2216

**Comment by tabatkins** [comment]
Agreed, done. I'll cut a new release in a little bit.

**Comment by svgeesus** [comment]
\0/
