### ISSUE TITLE
References to owner tabatkins should be replaced

### ISSUE THREAD

**Issue by gibson042** [speced/bikeshed#2462]
This repository and the rendered documentation at https://speced.github.io/bikeshed/ includes references to `tabatkins.github.io/bikeshed` and `github.com/tabatkins/bikeshed`, which should be replaced with `speced.github.io/bikeshed` and `github.com/speced/bikeshed` (respectively).

**Comment by tabatkins** [comment]
I *swear* that I replaced all of these already, but apparently I hallucinated that. Fixed, thanks.
