### ISSUE TITLE
Redirect to speced.github.io doesn't preserve `#deeplinks`

### ISSUE THREAD

**Issue by kainino0x** [speced/bikeshed#2466]
The redirection from `tabatkins.github.io/bikeshed` to `speced.github.io/bikeshed` doesn't preserve deeplinks by `#id`. For example, I tried to follow this link Tab sent a few weeks ago:
https://tabatkins.github.io/bikeshed/#dfn-contract
But it took me to
https://speced.github.io/bikeshed/
instead of
https://speced.github.io/bikeshed/#dfn-contract

**Comment by tabatkins** [comment]
Fixed!
