### ISSUE TITLE
Remote data is more than two days old

### ISSUE THREAD

**Issue by svgeesus** [speced/bikeshed#2477]
```
chris@SuperNomad:/mnt/c/Users/chris/Documents/GitHub/csswg-drafts/css-color-5$ bikeshed update
Updating via manifest...
Gathering local manifest data...
Fetching remote manifest data...
WARNING: Remote data is more than two days old; the update process has probably fallen over. Please report this!
Local data is already up-to-date with remote (2023-02-20 17:22:55)
```

**Comment by tabatkins** [comment]
Uhhhhh is your local time correct on your machine? As you can see, the remote data's date is today.

**Comment by svgeesus** [comment]
Yes, it is
![image](https://user-images.githubusercontent.com/2506926/220197342-171e36c6-6791-45ee-ad94-5857ccf4ffdf.png)

**Comment by nschonni** [comment]
Looks like the first command is running in WSL, is the time right in that machine?

**Comment by tabatkins** [comment]
Right; specifically, try running `date` in the WSL window?

**Comment by tabatkins** [comment]
(I should output both the last update time and the current detected machine time as part of this error, to make it clearer what might be the problem.)

**Comment by svgeesus** [comment]
> Looks like the first command is running in WSL

yes

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/GitHub/EuroMPE$ date
Tue Feb 21 14:30:12 EST 2023
```

Huh it is actually 2023-02-22 17:40 EST

OK, seems to be a weirdness on my end. Why would Ubuntu on WSL have a different date and time. Anyway, not a Bikeshed problem.

**Comment by tabatkins** [comment]
Keeping it open because I should actually display both the times I'm comparing, to make it easier to diagnose this sort of thing.
