### ISSUE TITLE
New HTML parser doesn't give sufficient information to solve issues

### ISSUE THREAD

**Issue by annevk** [speced/bikeshed#2498]
All I get is

> FATAL ERROR: Spurious / in &lt;a>.

for whatwg/fetch.

See https://github.com/whatwg/fetch/pull/1619 and https://github.com/whatwg/fetch/pull/1621 for sample PRs.

**Comment by tabatkins** [comment]
So this is indeed a *correct* error - you accidentally wrote `for/` instead of `for=/` in two tags, on line 870 and line 1139.

What's confusing me is that you're not getting the line and column where the error is occurring, as I'm getting it locally:

```bash
╰╴bikeshed -f spec
LINE 870:48: Spurious / in <a>.
LINE 1139:27: Spurious / in <a>.
```

**Comment by annevk** [comment]
🙏🏻
