### ISSUE TITLE
`<xmp>` broken on angle brackets

### ISSUE THREAD

**Issue by kainino0x** [speced/bikeshed#2500]
Seems like a regression in `<xmp>` handling between Bikeshed 3.11.16 and 3.11.17.

Example from WGSL spec:
https://github.com/gpuweb/gpuweb/blob/a6a54223ce5c383738c2f969171b59ac26447506/wgsl/index.bs#L2155

```
  <xmp highlight='rust'>
    fn foo(p : ptr<function, i32>) -> i32 {
      let x = *p;
      *p += 1;
      return x;
    }

    fn bar() {
      var a;
      let x = foo(&a); // the call to foo returns a value
                       // and updates the value of a
    }
  </xmp>
```

```
LINE 2154:15: Garbage at 2154:24 in <function>.
 ✘  Did not generate, due to fatal errors
```

https://github.com/gpuweb/gpuweb/issues/3995

**Comment by tabatkins** [comment]
Ohh I'm *very* surprised this would be happening, given part of this recent effort was specifically to avoid things like this. Sorry about that, I'll check it out asap.

**Comment by tabatkins** [comment]
fixed, sorry about that :///

**Comment by kainino0x** [comment]
No worries, thank you for the quick fix as always!
