### ISSUE TITLE
Broken link to Open Web Foundation Agreement Version 1.0

### ISSUE THREAD

**Issue by pietercolpaert** [speced/bikeshed#2509]
The current link is to http://www.openwebfoundation.org/legal/the-owf-1-0-agreements/owfa-1-0 which yields 404

probably needs to be updated to https://www.openwebfoundation.org/the-agreements/the-owf-1-0-agreements-granted-claims/owfa-1-0

Originally posted [here](https://github.com/SEMICeu/LinkedDataEventStreams/issues/30) by @marc-portier

**Comment by phochste** [comment]
Can this ticket be reopened? Every spec I generate from Bikeshed contains broken links in the header. The text says:


> CC0 To the extent possible under law, the editors have waived all copyright and related or neighboring rights to this work. In addition, as of 15 May 2024, the editors have made this specification available under the [Open Web Foundation Agreement Version 1.0](http://www.openwebfoundation.org/legal/the-owf-1-0-agreements/owfa-1-0), which is available at http://www.openwebfoundation.org/legal/the-owf-1-0-agreements/owfa-1-0. Parts of this work may be from another specification document. If so, those parts are instead covered by the license of that specification document.

Both links don't work. This is not only the case for my own specs but also the [Bikeshed documentation](https://speced.github.io/bikeshed/) itself contains broken links.

**Comment by tobie** [comment]
Could this be a Bikeshed boilerplate issue and the files needing to be fixed be those: https://github.com/search?q=repo:speced/bikeshed-boilerplate+Open+Web+Foundation+Agreement&type=code

**Comment by tabatkins** [comment]
Ah indeed, sorry about that, I just figured it was coming from a biblio link. Didn't realize it was directly in some of the boilerplates. ^_^

Fixed.
