### ISSUE TITLE
Cross-spec section links failing (after version 3.10.0)

### ISSUE THREAD

**Issue by svgeesus** [speced/bikeshed#2516]
[Cross-spec section links](https://speced.github.io/bikeshed/#section-links), of the form `[specname#id]` are failing in Bikeshed and generating fatal errors which must be suppressed with the `-f` option. For example (on the IFT specification):

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/GitHub/IFT$ bikeshed -f spec
LINE ~301: Couldn't find section '#name-get' in spec 'rfc9110':
[[rfc9110#name-get]]
LINE ~1093: Couldn't find section '#name-field-definitions' in spec 'rfc9111':
[[rfc9111#name-field-definitions]]
LINE ~1125: Couldn't find section '#name-accept-encoding' in spec 'rfc9110':
[[rfc9110#name-accept-encoding|Accept-Encoding]]
LINE ~1241: Couldn't find section '#name-field-definitions' in spec 'rfc9111':
[[rfc9111#name-field-definitions]]
LINE ~1259: Couldn't find section '#name-content-encoding' in spec 'rfc9110':
[[rfc9110#name-content-encoding|Content-Encoding]]
LINE ~1322: Couldn't find section '#name-freshness' in spec 'rfc9111':
[[RFC9111#name-freshness]]
LINE ~1460: Couldn't find section '#name-accept-encoding' in spec 'rfc9110':
[[rfc9110#name-accept-encoding|Accept-Encoding]]
LINE ~1602: Couldn't find section '#name-content-encoding' in spec 'rfc9110':
[[rfc9110#name-content-encoding|content encodings]]
 ✔  Successfully generated, but fatal errors were suppressed
```

Testing out the links manually, for example [https://www.rfc-editor.org/rfc/rfc9110#name-get](https://www.rfc-editor.org/rfc/rfc9110#name-get) shows they are correct. (I don't know if this is relevant, but all the failing specs are the HTTP set, such as RFC 9110, HTTP Semantics).

Originally reported:
 - https://github.com/w3c/IFT/issues/143

where it was also reported that

> something seems to have changed in bikeshed at the latest version. For now I've been able to get it to compile without errors using bikeshed 3.10.0

**Comment by tidoust** [comment]
This is probably due to the switch from Shepherd xref data to Webref xref data as a source. In Webref, RFC9110 gets crawled from https://httpwg.org/specs/rfc9110.html and not from https://www.rfc-editor.org/rfc/rfc9110

Unfortunately, the version on `httpwg.org` does not use the same IDs for anchors. For instance, [`#name-accept-encoding` ](https://www.rfc-editor.org/rfc/rfc9110#name-accept-encoding) in the `www.rfc-editor.org` version becomes [`#field.accept-encoding`](https://httpwg.org/specs/rfc9110.html#field.accept-encoding) in the `httpwg.org` version.

**Comment by svgeesus** [comment]
> Unfortunately, the version on httpwg.org does not use the same IDs for anchors.

HTTP WG breaks url consistency. Lol.

BTW the Bikeshed-generated html uses the `rfc-editor` links (which work). Odd.

**Comment by tabatkins** [comment]
Yup, that's the issue. Bikeshed will silently assume you know what you're talking about if the spec is in biblio data but not in headings data, but if it *is* in headings data, it verifies you're using the known IDs.

Hm tho, ideally SpecRef and WebRef are using the same URL for RFCs. It looks like SpecRef uses a mix of both origins, unfortunately.

**Comment by tabatkins** [comment]
(Closing as this isn't a Bikeshed issue.)
