### ISSUE TITLE
Force WPT block to show tests outside of the WPT directory

### ISSUE THREAD

**Issue by domfarolino** [speced/bikeshed#2522]
A spec I'm writing currently only has tests in Chromium's `wpt_internal/` directory that's not on GitHub. This is standard for an in-progress suite of tests that has not yet been moved to https://github.com/web-platform-tests/wpt/, and it would be great to be able to link to these totally-readable-and-useful WPTs from our spec until we move them over. That is, I'd love to have in my spec metadata:

```
WPT Path Prefix: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/wpt_internal/fenced_frame/
```

So that curious observers can at least read the tests even if they're not fully in the external repo yet. Then once they are all moved, we can just change the path prefix to the right external one and all of the `<wpt>` blocks still work. However this is not possible because if the path prefix contains a non-standard directory/URL, Bikeshed gives the understandable warning:

```
WARNING: Couldn't find WPT test 'https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/wpt_internal/fenced_frame/embedder-no-coep.https.html' - did you misspell something?
```

... even though that link is totally valid. I'd like us to consider loosening the checks on the resolved WPT links to allow links to WPT in non-standard directories. Of course you should not take advantage of this the closer your specification gets to standardization, but it would make the intervening period more rigorous by allowing the spec to point to tests.

**Comment by tabatkins** [comment]
All right, once I push a new version tomorrow, you'll be able to use `<wpt skip-existence-check>` and then use full URLs to random places. It'll just generate a link for you, instead of the several-part row that it does when it's a known WPT URL.
