### ISSUE TITLE
spec listed in "Terms defined by reference" twice

### ISSUE THREAD

**Issue by inexorabletash** [speced/bikeshed#2526]
https://w3c.github.io/IndexedDB/#index-defined-elsewhere

Has "[ECMA-262] defines the following terms:" twice, once for exported terms and once for non-exported terms pulled in via "&lt;pre class=anchors&gt;"

**Comment by inexorabletash** [comment]
Ugh, just noticed one is `[ECMA-262]` the other is `[ECMA262]` so this is probably not a bikeshed issue. Sorry!

**Comment by tabatkins** [comment]
Yeah, likely it's due to an anchors block defining a whole lot of JS terms, just with a slightly different spec name. Now that the JS spec is indexed by WebRef this *shouldn't* be necessary (but if there are some dfns still not being detected, we can get that fixed).

**Comment by inexorabletash** [comment]
Yeah, @tidoust did the awesome work to remove most of the terms. For this particular problem we had `spec: ecma262` instead of `spec: ecma-262`; it was an easy fix.

That said, I still have these remaining anchors:

```
spec: ecma-262; urlPrefix: https://tc39.github.io/ecma262/
    type: dfn; for: ECMAScript
        url: sec-algorithm-conventions
            text: !
            text: ?
        text: IdentifierName; url: prod-IdentifierName
        text: ReturnIfAbrupt; url: sec-returnifabrupt
        text: Type; url: sec-ecmascript-data-types-and-values
```

At least **!** and **?** and **Type** are also used by WebIDL so we should try and get those indexed; **ReturnIfAbrupt** can be replaced by **?** but at the expense of readability, so I'd prefer to keep it. **IdentifierName** is a weirdo and I'm guessing everyone (including me) would be happy to find a better replacement.
