### ISSUE TITLE
Silence warnings for autogenerated heading ID

### ISSUE THREAD

**Issue by CxRes** [speced/bikeshed#2548]
I am using headings that are simple enough that autogenerated IDs will remain consistent. Can I silence the warnings for autogenerated ID for headings?

**Comment by tabatkins** [comment]
Yes, by adding an id attribute to them. ^_^ (I find that even "simple" headings end up changing, if only slightly, rather often.)

**Comment by CxRes** [comment]
I can live with that! But you must accept that it is not nice for readability. A flag would be nice in the future...
