### ISSUE TITLE
Links to HTTP header definitions are wrapped in both <code> and backticks

### ISSUE THREAD

**Issue by CxRes** [speced/bikeshed#2572]
Define a http header:

```html
<dfn data-dfn-type="http-header">Accept</dfn>
```

Link to this header:

```md
[:Accept:]
```

Output is: 

```html
<span>
  `
    <code>
      <a data-link-type="http-header" href="#http-headerdef-accept" id="ref-for-http-headerdef-accept">Accept</a> 
   </code>
  `
</span>
```

This is very strange. Backticks should not be there...

**Comment by tabatkins** [comment]
This is intentional - the backticks are part of the preferred formatting for references to HTTP headers, since they're bytestrings.

**Comment by CxRes** [comment]
@tabatkins Hang on! HTTP headers are bytestrings only in HTTP/2 onwards (See RFC9111 pointing to RFC5322 using ASCII). I have seen multiple versions of RFC9110 (the standard that defines the concept of headers) where ordinary quotes are being used for header fields.

**Comment by CxRes** [comment]
At the very least, if the quotes were introduced using CSS and not "hardcoded", one could override them.
