### ISSUE TITLE
Problem with bibliographic entries

### ISSUE THREAD

**Issue by HelgeKrueger** [speced/bikeshed#2577]
Hi. I tried to link to [activitypub](https://www.specref.org/?q=activitypub) from a bikeshed file. The reference generated is:

[ACTIVITYPUB]
    Christopher Webber; Jessica Tallon. [ActivityPub](https://w3c.github.io/activitypub/). URL: https://w3c.github.io/activitypub/

here the link goes to the repository instead of the href. Is there a way to configure bikeshed to link to the href? Or is this a bug?

**Comment by tabatkins** [comment]
I apologize, but I'm not sure what you mean by "the link goes to the repository instead of the href". Both of those links in the biblio are to the ED of the spec.

**Comment by HelgeKrueger** [comment]
Thanks for your reply. I think that would be the right formulation. I don't want to link to the ED (= Editor's Draft), but to the W3C Recommendation. It's https://www.w3.org/TR/activitypub/ in this case.

The same issue arises in https://speced.github.io/bikeshed/#normative The first link points to the the Editor's draft (https://drafts.csswg.org/css-flexbox-1/) and not the recommendation (https://www.w3.org/TR/css-flexbox-1/) or Latest Published Version.

This seems like an odd choice to me, as I would expect the published version to have precedence.

**Comment by tabatkins** [comment]
Ah, Bikeshed has information about both the "current" (usually an ED) and the "snapshot" version (usually a `w3.org/TR` publication). It automatically defaults to one or the other based on whether *your* spec is using a "current" or "snapshot" status. For example, in an ED you'll default to using ED links, in a CR you'll default to using snapshot links.

You can change the default for your whole spec by using the [`Default Ref Status` metadata](https://speced.github.io/bikeshed/#metadata-default-ref-status), or select it for a single biblio by adding a tag, like `[[ACTIVITYPUB snapshot]]`.

**Comment by HelgeKrueger** [comment]
Thanks! That solved my issue.
