### ISSUE TITLE
api.csswg.org/bikeshed server always returns HTML instead of accepting files

### ISSUE THREAD

**Issue by domenic** [speced/bikeshed#2608]
Test:

```
curl https://api.csswg.org/bikeshed/ -F file=@notifications.bs -F force=1 > test.html
```

The output in `test.html` appears to be roughly the same as the source code I can see in `view-source:https://api.csswg.org/bikeshed/`. It didn't actually process my document.

@plinss

**Comment by plinss** [comment]
Disk was full on the server, should be fixed now
