### ISSUE TITLE
bikeshed update not working due to 400 on download

### ISSUE THREAD

**Issue by woutermont** [speced/bikeshed#2624]
I'm trying to run `bikeshed update` (v3.14.3), but get the following fatal error.

```
❯ bikeshed update
Updating via manifest...
Gathering local manifest data...
Fetching remote manifest data...
WARNING: Previous update had some download errors, so re-running...
Updating 10 files...
WARNING: Error downloading , full error was:
400, message='Bad Request', url=URL('https://raw.githubusercontent.com/tabatkins/bikeshed-data/master/data/')
Updated 9/10, 1 errors...
FATAL ERROR: Done, but there was 1 error (of 10 total) in downloading or saving. Run `bikeshed update` again to retry.
 ✘  Did not generate, due to fatal errors
```

**Comment by tabatkins** [comment]
Hm, I'm confused in two regards here.

First, I updated that URL a week before the last release; it should be `main` now. Unsure why you're seeing `master` if you're on 3.14.3.

Second, hm, that error implies you're trying to download a file with an empty path. But there isn't any such file in [the manifest](https://github.com/speced/bikeshed-data/blob/main/data/manifest.txt). I wonder if you're trying to download the second line, tho, which is a version number. If so, that definitely implies you're actually running an old version.

Can you confirm that `bikeshed --version` gives `3.14.3`?

**Comment by woutermont** [comment]
```
❯ pipx upgrade bikeshed 
bikeshed is already at latest version 3.14.3
```

```
❯ bikeshed --version
3.14.3
```

🤷‍♂️

**Comment by woutermont** [comment]
As discussed in [#tabatkins_bikeshed:gitter.im](https://matrix.to/#/#tabatkins_bikeshed:gitter.im), this is no longer an issue for me, so for me this can be closed.

**Comment by tabatkins** [comment]
I'm gonna go ahead and close this, but if anyone else runs into this (and running `pipx upgrade bikeshed` doesn't help), please let me know and we can re-open.

**Comment by tpluscode** [comment]
Hi. I am stuck at 3.11.14 (re #2479) and now `bikeshed update` stopped working when I do

I find that I can live without it but I don't understand the implication
