### ISSUE TITLE
Bad error message for IDL syntax errors

### ISSUE THREAD

**Issue by cbiesinger** [speced/bikeshed#2650]
I got:
```
FATAL ERROR: IDL SYNTAX ERROR LINE: 2 - skipped: "dictionary SignInStatusOptions {
    boolean idp;
  }"
```

I don't know yet what the error is, but this message is not super helpful in figuring it out.

**Comment by tabatkins** [comment]
Unfortunately I only get what information is given to me by `widlparser`; since it's grammar-based, all it gets is "this isn't valid grammar for the current spot".

Without implementing my own WebIDL parser, I don't think I can improve these meaningfully.
