### ISSUE TITLE
`simpledef` block breaks auto links due to forced lowercasing

### ISSUE THREAD

**Issue by Ethan-Arrowood** [speced/bikeshed#2654]
Given the following markup:

```bs
<pre class="idl">
[Exposed=*]
interface F {
    string mymethodwithoutcaps();
    string myMethodWithCaps();
};
</pre>

<pre class="simpledef">
{{mymethodwithoutcaps()}} : i autolink correctly
{{myMethodWithCaps()}} : i don't autolink inside a simpledef
</pre>

But I do autolink outside a simpledef: {{myMethodWithCaps()}}
```

The method with capitalization does not render/autolink correctly due to the forced lower casing in the `simpledef` block.

<img width="524" alt="Screenshot 2023-09-01 at 11 24 33" src="https://github.com/speced/bikeshed/assets/16144158/bb4fffe0-6f80-4d90-b823-b6ead245cacc">

**Comment by tabatkins** [comment]
I'm not really sure why I'm lowercasing in the first place. I'll fix.

**Comment by Ethan-Arrowood** [comment]
Thank you @tabatkins !

**Comment by tabatkins** [comment]
Fixed; I'll let the bots run *just in case* and then cut a new version.

**Comment by Ethan-Arrowood** [comment]
Thank you so much!
