### ISSUE TITLE
A mode that fails on warnings, but shows all of them

### ISSUE THREAD

**Issue by domenic** [speced/bikeshed#2669]
In WHATWG we use `--die-on=warning` to ensure our specs build with no warnings.

However, this has the unfortunate result that if our spec has two lines that cause warnings, we only see one of them, because (as requested) Bikeshed dies on the first one.

Could we instead have some sort of mode that still outputs all the warnings, but refuses the build the spec, and exits with a nonzero exit code, if the number of warnings is > 0?

We can work around this today by switching off `--die-on=warning` temporarily, but something built-in would be nicer.

**Comment by tabatkins** [comment]
Hm, yeah, I can do this.

**Comment by tabatkins** [comment]
Actually, quick question: is the current behavior useful at all? Is it *good* to have something that stops processing on the first message that it'll die on? Or should I just generally flip the behavior over to what you're requesting, where all the messages print, but it'll refuse to actually save the output and exit with an error?

**Comment by domenic** [comment]
I'm not sure whether I would personally use the current behavior. But I can imagine situations where you have hundreds of errors or warnings (due to some cascading error, e.g. missing end tags or something), and in that case it might be more helpful. I think for that reason test runners often have a non-default "die-on-first-test-failure" feature.

But yeah, if you just switched everything over, that would not be a problem for me.

**Comment by tabatkins** [comment]
Done. Bikeshed now defaults to dying only at the end of generation, so you'll see all the messages, but still get a non-zero exit code and no output document. You can control this with `--die-when` or the `Die When` metadata.

**Comment by tabatkins** [comment]
(Rather, it will when I cut my next release.)
