### ISSUE TITLE
Unexpected `title` value of anchor links

### ISSUE THREAD

**Issue by cdoublev** [speced/bikeshed#2679]
The `title` of the HTML anchor link for the [`<box>`](https://drafts.csswg.org/css-backgrounds-3/#typedef-box) CSS type is:

  > Expands to: `border-box | content-box | fill-box | margin-box | padding-box | stroke-box | svg viewport origin box | view-box`

But it is defined with `border-box | padding-box | content-box`.

![issue](https://github.com/speced/bikeshed/assets/15889080/6306e735-c484-438d-8b7b-e5dca7e26804)

I am not sure how it is generated. I cannot find `svg viewport origin box` in any CSS spec. I guess it is a caching issue.

**Comment by tabatkins** [comment]
That definition comes from <https://www.w3.org/TR/css-box-3/#valdef-box-stroke-box>; all of those keywords are defined for `<box>` as well as the more specific `<*-box>` productions.

(B&G needs to update to use `<visual-box>`, rather than redefining.)

**Comment by tabatkins** [comment]
k, B&G markup fixed (and while I was in there, fixed all the other Bikeshed errors so it builds clean now)

**Comment by cdoublev** [comment]
Out of curiosity, what does *B&G* means? Did you mean B&B? (Backgrounds and Borders)

---

I hope it is ok if I do not open a separate issue. Can you please also fix the references to `<box>` in [CSS Shapes 1](https://drafts.csswg.org/css-shapes-1/#typedef-shape-box) and [CSS Backgrounds 4](https://drafts.csswg.org/css-backgrounds-4/#typedef-bg-clip)?

Also, `<visual-box>` values are namespaced to `background-clip` instead of `<visual-box>`:

  > ```html
  > <p>Values have the following meanings:
  >
  > <dl dfn-for=background-clip dfn-type=value>
  >   <dt><dfn>border-box</dfn></dt>
  > ```

So it results to the equivalent data in `w3c/reffy`:

```
"properties": [
  {
    "name": "background-clip",
    "value:" "<visual-box>#",
    "values": [
      { "name": "border-box", ... }
      ...
    ],
  },
  {
    "name:" "background-origin",
    "value": "<visual-box>#",
    "values": [], // empty
  },
]
```

Is it correct to assume that a production rule (the expanded values) is context-insensitive, even if its interpretation can be defined specifically for a given context?
