### ISSUE TITLE
Use `revision` rather than `document-revision` in `<meta>`

### ISSUE THREAD

**Issue by dontcallmedom** [speced/bikeshed#2692]
Bikeshed uses `<meta name=document-revision>` to document the commit used to generate its HTML output.

There is a [documented extension](https://wiki.whatwg.org/wiki/MetaExtensions) for this which uses simply [`name=revision`](https://github.com/krallin/meta-revision); I understand that `revision` is also used with a different meaning in the bikeshed context, but would there be any objection to aligning with the documented extension? Happy to provide a PR if that's acceptable.

(I'm in the process of bringing similar support in [ReSpec](https://github.com/w3c/respec/pull/4561) + [spec-prod](https://github.com/w3c/spec-prod/pull/167), using `revision` atm)

**Comment by tabatkins** [comment]
Sure, I just made up a word [back when I first added it](https://github.com/speced/bikeshed/issues/1063), I'm happy to change it.
