### ISSUE TITLE
Auto-detect `value` rather than `type` when there is a bracketed range

### ISSUE THREAD

**Issue by cdoublev** [speced/bikeshed#2719]
[`<time [0s,∞]>`](https://drafts.csswg.org/css-animations-1/#typedef-animation-duration-time-0s) is automatically defined with `data-dfn-type="type"`. I would expect `data-dfn-type="value"`, like for [`<number [0,∞]>`](https://drafts.csswg.org/css-animations-1/#valdef-animation-iteration-count-number-0), as I think that a range notation can only qualify a type if it is in the right side of a production (as a value), not the left side (as a type).

The [source text](https://github.com/w3c/csswg-drafts/blob/7dc0ecd785c74d6b1658aaa2594c49930aee5e68/css-animations-1/Overview.bs#L511) is a naked `<dfn>` contained in `<dl dfn-value dfn-for=animation-duration>`, since this relatively recent [change](https://github.com/w3c/csswg-drafts/commit/f1332c855a46e5c00d3080dcc0817e2c3034ecca#diff-ac4f94e3eefcfce927804192e5f2392840a849f445a075f3e901f2aeb63f9b28L511).

It is a [minor problem](https://github.com/w3c/webref/blob/8041d854bda55772a9157c4ad4ca0a1da0c97e7e/ed/css/css-animations.json#L48-L50) but hopefully it can be easily fixed.

**Comment by tabatkins** [comment]
Yes, this makes sense.

**Comment by tabatkins** [comment]
Fixed in 70d45df24
