### ISSUE TITLE
WPT piecharts not displayed for tests outside the path prefix

### ISSUE THREAD

**Issue by svgeesus** [speced/bikeshed#2763]
For example (from CSS Color 4)

![image](https://github.com/speced/bikeshed/assets/2506926/8ed2ba66-7d52-41a1-92c0-65d42280a435)

Here we have, in the metadata block

```html
WPT Path Prefix: css/css-color/
``` 

and then in the spec,

```html
<wpt>
	tagged-images-001.html
	tagged-images-002.html
	tagged-images-003.html
	tagged-images-004.html
	/png/cicp-chunk.html
</wpt>
```

Notice that, because of the initial `/`, in the generated html the test link, the `(live test)` and the `(source)` all have correct working links. It is just the pie charts of results that are not displayed, presumably because they are outside the path prefix. I guess the code that generates them considers that the path prefix is _always_ applied, rather than checking first for an initial `/`.

The workaround is awkward: don't use a path prefix at all and give the full path for all tests. It would be much nicer to use a path prefix while still allowing the few tests that live outside that to be reported correctly.

Possibly related to 

 - https://github.com/speced/bikeshed/issues/1414

although I suspect not.

**Comment by svgeesus** [comment]
Oh, I also tried this 

```html
<wpt>
	tagged-images-001.html
	tagged-images-002.html
	tagged-images-003.html
	tagged-images-004.html
</wpt>

<wpt pathprefix="/png">
	cicp-chunk.html
</wpt>
```

but it made no difference.

**Comment by tabatkins** [comment]
> I guess the code that generates them considers that the path prefix is always applied, rather than checking first for an initial /

Correct. I didn't think of treating them like abs/rel paths; currently I just concatenate them (and ensure there's exactly one slash between them, not 0 or 2). I should probably change to abs/rel, tho I'd need to do some safety checks - if a slash-prefixed path fails, but treating it as relative works, I'd emit a warning and treat it as relative.

> `<wpt pathprefix="/png">`

Hm, that should work, I'll check on it.

**Comment by tabatkins** [comment]
Ah, right, it doesn't generate the pie chart because I only pull one path-worth of WPT data currently; by default, I just use the provided `WPT Path Prefix` metadata. That is indeed not great; it looks like Color also lists tests from three other directories.

Fixed now, just rebasing tests so I can do a release.
