### ISSUE TITLE
Definition tooltips sometimes overlap the text they're attached to, in Firefox

### ISSUE THREAD

**Issue by kainino0x** [speced/bikeshed#2771]
Originally posted by @guusw here: https://github.com/gpuweb/gpuweb/issues/4457#issue-2090264894

> When hovering over specific sections while viewing the spec in a browser (specifically firefox/librewolf) the popup will sometimes overlap the link I want to click.
> The most notable example is in https://www.w3.org/TR/WGSL/#address-space
> Might be specific to these kind of tables
> 
> ![erqrqr](https://github.com/gpuweb/gpuweb/assets/16842774/03d103ca-8ae8-415b-8960-1e50a237e059)

**Comment by kainino0x** [comment]
I agree it's likely that this is due to the fact that the ref link is in a table. It's also possible that it's somehow specific to styling we use in the WGSL spec.

**Comment by tabatkins** [comment]
That is.... very strange. Some experimentation shows it's the `<caption>` that's causing the issues - the tooltip is misaligned by exactly the caption's height. That implies the OM operation I'm doing to accumulate the scroll offset, when asked about the table's offset, answers the question about the *table grid*, not the *table wrapper box*, in Firefox. That is probably wrong! I'll make a reduced test case and report it on Firefox.

**Comment by tabatkins** [comment]
OKAY, I tracked down the issue and reported it on Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1876640

In the meantime, there's a different, easier way to calculate this offset that we can use instead, which works correctly in all cases.

**Comment by tabatkins** [comment]
Fixed in version 4.1.3
