### ISSUE TITLE
Turn of the splitting of a word onto the next line

### ISSUE THREAD

**Issue by healytpk** [speced/bikeshed#2805]
Let's say a paper contains a very long word such as antidisestablishmentarianism. If this word is near the right-hand side of the screen, it will be split into two lines, something like:
```
With regard to the young child's understanding of antidisest-
ablishmentarianism, we have ascertained that the child has
no understanding of the term.
```
I want to disable the splitting of words for the entire document -- I don't find it cosmetically attractive and I find that it hinders a person's reading. In rare cases it can introduce ambiguity where two words are distinguished only by a hyphen.

**Comment by tabatkins** [comment]
This is being caused by the Bikeshed default styles having `hyphens: auto;` on `<body>`. Feel free to turn it off with the following style block in your document:

```html
<style>
body {
  hyphens: manual;
}
</style>
```
