### ISSUE TITLE
nodejs favicon URL changed?

### ISSUE THREAD

**Issue by himorin** [speced/bikeshed#2823]
[mdn-anno.css](https://github.com/speced/bikeshed/blob/ea552a8aeeec7a39d1582f2b9fa4544b301249fc/bikeshed/mdn/mdn-anno.css#L178C24-L178C77) has favicon line as

> background-image: url(https://nodejs.org/static/images/favicons/favicon.ico);

but it seems URL has gone and returns 404. I have no idea on new location, so just file an issue here.

**Comment by tabatkins** [comment]
Sigh, thanks for the reports. I'll track it down and I guess just download the image directly.

**Comment by himorin** [comment]
it seems we could replace with https://nodejs.org/favicon.ico
