### ISSUE TITLE
DL/DTs in W3C EDs increment OL/LI counts

### ISSUE THREAD

**Issue by inexorabletash** [speced/bikeshed#2832]
Reported at https://github.com/w3c/IndexedDB/issues/418

If you have a DL within an OL, the DTs cause the list count to increment.

Minimal repro:
```
<pre class=metadata>
Group: webapps
Status: ED

Title: anything
Shortname: anything
Abstract: anything
ED: anything
Level: anything
Editor: anything
Repository: anything
</pre>

<div algorithm>

To <dfn export>foo</dfn>:

1. This should be number 1.

    <dl class=switch>

      : term
      :: definition

      : term
      :: definition

    </dl>

1. This should be number 2.

</div>
```

Renders as:
![image](https://github.com/speced/bikeshed/assets/771547/b2c55060-e904-48f6-9fc7-76de49c0e951)

Inspecting the rendered page shows this selector/style seems to be the root cause: 
```
dl.switch > dt {
    display: list-item;
}
```
... coming from W3C's base.css I guess? So this is probably not Bikeshed's fault _per se_.

**Comment by tabatkins** [comment]
Filed <https://github.com/w3c/tr-design/pull/351> to fix it upstream.

**Comment by tabatkins** [comment]
(The existing W3C stylesheet *should* work; it scopes the list-item counter to `dl` so that should block it from screwing with the `ol`'s counter. I suspect Chrome's implementation of `ol` counters is still non-conformant to the spec.)
