### ISSUE TITLE
Option to omit spec's status 

### ISSUE THREAD

**Issue by raimundo-henriques** [speced/bikeshed#2835]
First and foremost: thanks for your great work!

I have recently come across a situation where we would like to omit the spec's status altogether. We would like to be able to keep one version with LD and another without any indication of status.

Currently, this is only possible through the use of a `header.include` without the `[LONGSTATUS]` `h2`.

Have you considered covering this option in the Metadata itself (which would make it possible to remove the status with the `--md-status` flag)?

Thank you!

**Comment by tabatkins** [comment]
Hm, could you elaborate more on your use-case here, so I can understand what options there might be? (Usually the answer is indeed to use a separate boilerplate file that just uses different markup.)

**Comment by raimundo-henriques** [comment]
Dear @tabatkins,

Thank you for your answer! We ended up using separate boilerplates. 

In any case, just to be clear, the use case was one where we did not want the rendered specs to have any explicit status whatsoever (which would in that particular case be understood as being a release). 

I am sorry for the inconvenience and I believe this issue can be closed.

Thank you!
Best,
