### ISSUE TITLE
Document diff mode

### ISSUE THREAD

**Issue by caraitto** [speced/bikeshed#2855]
The diff mode feature I see on pull requests is very useful. Here's how I access it:

1. Modify a spec, build the diff. For instance, click on the "Diff" link in the "Preview | Diff" section of https://github.com/WICG/turtledove/pull/1180. (I'm not sure how to do this from the command line, it doesn't seem to be documented -- maybe it's another tool and not Bikeshed that does this, or maybe not? I couldn't figure it out looking at the GitHub build log for that PR.)

The [Bikeshed documentation](https://speced.github.io/bikeshed/) doesn't mention this at all though, AFAICT? Neither does `bikeshed --help`.

It would be nice to mention how to build a diff from the command line. Also, it would be nice to document keyboard shortcuts, like "j" and "k", and the next, back and 1 of N UI widget at the bottom right.

If this isn't a Bikeshed feature, do you know how the diff page gets built by the GitHub action?

**Comment by leo-barnes** [comment]
I just ran into the exact same issue.
Ended up having to create a temporary pull request just to generate the diff document.

**Comment by tabatkins** [comment]
Right, it's not documented because that's not something I'm responsible for at all. ^_^ That's [tobie's pr-preview](https://github.com/tobie/pr-preview).

**Comment by caraitto** [comment]
Ah, interesting, looks like that GitHub action [0] invokes a service [1] that wraps a Perl script [2] that produces HTML that embeds this navigation script [3] that supports keyboard shortcuts "j", "k", and "escape" (to cancel movement) in addition to the UI buttons.

Presumably, you could run htmldiff.pl locally with the old and new HTML rendered specs to produce the same result.

[0] https://github.com/tobie/pr-preview
[1] https://services.w3.org/htmldiff
[2] https://github.com/w3c/htmldiff-ui/blob/main/htmldiff.pl
[3] https://github.com/w3c/htmldiff-nav/blob/ab28ebba333cc88407da0621f046c8f10eed1d52/index.js#L121
