### ISSUE TITLE
Curly apostrophes not consistent

### ISSUE THREAD

**Issue by clelland** [speced/bikeshed#2884]
It appears that source like this:

```
   a <a>Document<a>'s title
```

will have its apostrophe curlified, like this:

> <p>a <a data-link-type="dfn" href="https://dom.spec.whatwg.org/#concept-document" id="ref-for-concept-document">Document</a>’s title</p>

while this source:

```
   a [=Document=]'s title
```

will retain its sad, uncurlified single-quote:

> <p>a <a data-link-type="dfn" href="https://dom.spec.whatwg.org/#concept-document" id="ref-for-concept-document①">Document</a>'s title</p>

Is this intentional, or a bug in the parser?

**Comment by tabatkins** [comment]
Bug in the parser, but it's fixed in the upcoming parser rewrite I'll be merging into main after I get back from vacation. 😃
