### ISSUE TITLE
Tracking-vector image should be marked darkmode-aware

### ISSUE THREAD

**Issue by Kaiido** [speced/bikeshed#2905]
In https://github.com/whatwg/whatwg.org/pull/444 the tracking-vector svg from whatwg has been made darkmode-aware, however for it to render properly without a white background, it needs a `class="darkmode-aware"`.

Looking at [the source](https://github.com/speced/bikeshed/blob/26c78a10d73876e96a126dbf7599eab4d0d998ed/bikeshed/fingerprinting.py#L17) it seems there is an inline fallback that is not darkmode-aware. It also seems that every consumer could define their own source for the image file? That would probably make things harder to fix.

**Comment by tabatkins** [comment]
Ooh, thanks for pointing this out. I've gone ahead and made my inline image darkmode-aware, and added the class to the generated img. I've noted in the docs that the external image (if provided) must be darkmode-aware as well.
