### ISSUE TITLE
Ref-hints are broken in the dark theme

### ISSUE THREAD

**Issue by MeFoDy** [speced/bikeshed#2907]
My friend found an issue during the [CSS Color](https://www.w3.org/TR/css-color-4/#legacy-color-syntax) spec reading. If you click on the text `legacy color syntax` with system dark theme enabled, the popup will look like this.

<details>
  <summary>Issue screenshot</summary>
  <img src="https://github.com/user-attachments/assets/9dfe2bae-a2b7-4c26-b406-63e9ab6b6cfb" alt="">
</details>

I think the problem is here:
https://github.com/speced/bikeshed/blob/0474eae152d6c8f278bd9dbdd76449415c71484c/bikeshed/refs/ref-hints.css#L8

**Comment by numbingmist** [comment]
Browser data for test cases: 
Google Chrome
Version 127.0.6533.100 (Official Build) (arm64)
Default color-scheme = dark

**Comment by tabatkins** [comment]
This has [already been fixed](https://github.com/speced/bikeshed/commit/1232e02e498febeaff97006a7b8bc275c9769f78), unfortunately a month after that spec was last published. More recent specs properly indicate that they're darkmode-capable and get the correct set of color variables from the dark-mode W3C stylesheet.
