### ISSUE TITLE
Provided custom definitions are all lowercase

### ISSUE THREAD

**Issue by leo-barnes** [speced/bikeshed#2941]
See this issue for context: https://github.com/AOMediaCodec/av1-avif/issues/281

Even though we specify the `text` in the `<pre class="anchors">` with uppercase characters, the "Terms defined by reference" section has them all as lowercase. As an example, see PixelInformationProperty in https://aomediacodec.github.io/av1-avif/#index-defined-elsewhere.

From [section 6.8](https://speced.github.io/bikeshed/#custom-dfns) in the Bikeshed spec, I can see that the `text` is used as part of the URL when a URL prefix is added. It makes sense that the URL is all lowercase, but I don't think the actual text for the term that shows up in the "Terms defined by reference" section should be lowercase.

**Comment by tabatkins** [comment]
Yup, this is an old issue, #861. I have a plan in that issue to fix it, I just never got around to implementing it. Let me do so, I think it looks simple.

**Comment by tabatkins** [comment]
And yup, should be fixed in latest Bikeshed. There's a very mild heuristic to try and detect if a dfn is capitalized only because it happened to start a sentence, and lowercase it in that case, but otherwise original casing is preserved for all definitions.
