### ISSUE TITLE
Bikeshed generating error  -- Something's gone wrong with the remote data; I can't read its timestamp. Please report this!

### ISSUE THREAD

**Issue by daniel-montalvo** [speced/bikeshed#2949]
I got this error while trying to build ACT-Rules-format-1.1
For full context, see
Something's gone wrong with the remote data; I can't read its timestamp. Please report this!

Is there anything we should be updating in the spec?

**Comment by tabatkins** [comment]
Not in your spec, but in your CI - likely, you're specifying an old Ubuntu, which only has Python 3.8, so you've actually been stuck on an old Bikeshed for a while now. See <https://github.com/speced/bikeshed/issues/2946>

(Alternately, if you're building locally, you just have an old Python. Update to at least Python 3.9, and then `pip install --upgrade bikeshed`)

**Comment by daniel-montalvo** [comment]
thanks, that was indeed the reason for the failure.
