### ISSUE TITLE
Remove mentions of Typed Array from the repository

### ISSUE THREAD

**Issue by annevk** [speced/bikeshed#462]
Typed Array is no longer a thing. References should most likely go to IDL directly. In a few cases ECMAScript itself is referenced.

**Comment by annevk** [comment]
For instance, https://github.com/tabatkins/bikeshed/blob/master/bikeshed/spec-data/readonly/specs.json contains it.

**Comment by annevk** [comment]
I'm happy to provide PRs by the way, if that helps. But I'm not quite sure how everything works yet so somewhat hesitant.

**Comment by tabatkins** [comment]
Sure, I can remove that.  It's a generated file; I'd have to remove it from Shepherd.  In the meantime I need to handle WebIDL. >_<

**Comment by tabatkins** [comment]
Looks like I'll finally be able to do this soon, once WebIDL is finished converting to Bikeshed!

**Comment by jyasskin** [comment]
I think this is done: https://github.com/search?q=repo%3Aspeced%2Fbikeshed%20%22Typed%20Array%22&type=code
